"""empty message

Revision ID: 1a0fc55a5df2
Revises: 
Create Date: 2024-06-05 15:35:37.647425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a0fc55a5df2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('contenent', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('mannerism', sa.String(), nullable=True),
    sa.Column('visa', sa.String(), nullable=True),
    sa.Column('tipping', sa.String(), nullable=True),
    sa.Column('when', sa.String(), nullable=True),
    sa.Column('links', sa.String(), nullable=True),
    sa.Column('phrases', sa.String(), nullable=True),
    sa.Column('foods', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('favorite_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['favorite_id'], ['favorites_table.id'], name=op.f('fk_countries_table_favorite_id_favorites_table')),
    sa.ForeignKeyConstraint(['user_id'], ['users_table.id'], name=op.f('fk_countries_table_user_id_users_table')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorites_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries_table.id'], name=op.f('fk_favorites_table_country_id_countries_table')),
    sa.ForeignKeyConstraint(['user_id'], ['users_table.id'], name=op.f('fk_favorites_table_user_id_users_table')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('_hashed_password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_table')
    op.drop_table('favorites_table')
    op.drop_table('countries_table')
    # ### end Alembic commands ###
